name: Production Environment Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull vercel environment variables
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} 
        
      - name: Build project artifacts
        run:  vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} 
      
      - name: Deploy project artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 